server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eee?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  devtools:
    restart:
      enabled: true